import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import MessengerChatButton from "@/components/plugin/MessengerWidget";
import ZaloChatWidget from "@/components/plugin/ZaloChatWidget";
import Header from "@/components/molecules/Header";
import HeaderImageLayout from "@/components/molecules/HeaderImageLayout";
import Footer from "@/components/molecules/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "X-Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="img-src https: data:; upgrade-insecure-requests"
        />
      </Head>
      <body className={`${inter.variable} relative`}>
        <div className="fixed bottom-0 right-0 z-50">
						<MessengerChatButton />
						<ZaloChatWidget />
					</div>
        <Header />
      
        {children}
        <Footer />
      </body>
    </html>
  );
}
